# Generated by Django 6.0.4 on 2026-05-14 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('replaced', 'Replaced'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('activation_requested', 'Activation Requested'), ('activation_confirmed', 'Activation Confirmed'), ('activation_rejected', 'Activation Rejected'), ('deactivated', 'Deactivated')], max_length=30),
        ),
        migrations.CreateModel(
            name='DelegationActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_activations', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='users.delegation')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_activations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('delegation',), name='one_pending_activation_per_delegation')],
            },
        ),
    ]
