# Generated by Django 6.0.3 on 2026-03-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_consentpolicy'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='CustomPermission',
        ),
    ]
