# Generated by Django 6.0.4 on 2026-05-11 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid UK postcode', regex='^[A-Z]{1,2}\\d[A-Z\\d]?\\s?\\d[A-Z]{2}$')]),
        ),
    ]
