# Generated by Django 6.0.3 on 2026-04-21 23:34

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")

    roles = [
        "subject",
        "processor",
        "regulator",
        "researcher",
        "insurance_agent",
    ]

    for role_name in roles:
        Role.objects.get_or_create(name=role_name)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_permission_custompermission"),
    ]

    operations = [
        migrations.RunPython(create_roles, migrations.RunPython.noop),
    ]