# Generated by Django 6.0.5 on 2026-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_delegationlog_action_delegationactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('replaced', 'Replaced'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('activation_requested', 'Activation Requested'), ('activation_confirmed', 'Activation Confirmed'), ('activation_rejected', 'Activation Rejected'), ('deactivated', 'Deactivated')], max_length=30),
        ),
    ]
