# Generated by Django 6.0.3 on 2026-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delegation_delegationlog_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delegation',
            name='one_active_delegation_per_subject',
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('active', 'Active'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='delegationlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('replaced', 'Replaced'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('activation_requested', 'Activation Requested')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='delegation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'active'])), fields=('data_subject',), name='one_active_delegation_per_subject'),
        ),
    ]
