# Generated by Django 6.0.3 on 2026-04-25 10:59

from django.db import migrations


DEFAULT_ROLE_MATRIX = {
    "subject": {
        "diagnosis": ["read"],
        "treatment": ["read"],
        "mental_health": ["read"],
        "billing": ["read"],
        "lab_results": ["read"],
        "medication": ["read"],
        "allergies": ["read"],
        "immunization": ["read"],
    },
    "processor": {
        "diagnosis": ["read"],
        "treatment": ["read", "update"],
        "billing": ["read"],
        "lab_results": ["read"],
        "medication": ["read"],
        "allergies": ["read"],
        "immunization": ["read"],
    },
    "researcher": {
        "diagnosis": ["read"],
        "lab_results": ["read"],
        "immunization": ["read"],
    },
    "insurance_agent": {
        "billing": ["read"],
        "treatment": ["read"],
    },
    "regulator": {
        "diagnosis": ["read"],
        "treatment": ["read"],
        "billing": ["read"],
        "lab_results": ["read"],
        "medication": ["read"],
        "allergies": ["read"],
        "immunization": ["read"],
    },
}


def get_or_create_by_name(Model, name):
    obj = Model.objects.filter(name=name).first()
    if obj:
        return obj
    return Model.objects.create(name=name)


def seed_default_role_permissions(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    CustomPermission = apps.get_model("users", "CustomPermission")
    RolePermission = apps.get_model("users", "RolePermission")

    for role_name, matrix in DEFAULT_ROLE_MATRIX.items():
        role = get_or_create_by_name(Role, role_name)

        for category, actions in matrix.items():
            for action in actions:
                permission_name = f"can_{action}_{category}_records"
                permission = get_or_create_by_name(CustomPermission, permission_name)

                exists = RolePermission.objects.filter(
                    role=role,
                    permission=permission,
                ).exists()

                if not exists:
                    RolePermission.objects.create(
                        role=role,
                        permission=permission,
                    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_seed_roles"),
    ]

    operations = [
        migrations.RunPython(
            seed_default_role_permissions,
            migrations.RunPython.noop,
        ),
    ]