# Generated by Django 6.0.5 on 2026-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('research', 'Research'), ('audit', 'Audit'), ('emergency', 'Emergency'), ('insurance', 'Insurance')], max_length=50)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('share', 'Share'), ('delete', 'Delete')], default='read', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('evaluated', 'Evaluated')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('data_type', models.JSONField(blank=True, default=list)),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('research', 'Research'), ('audit', 'Audit'), ('emergency', 'Emergency'), ('insurance', 'Insurance')], default='research', max_length=100)),
                ('consent_type', models.CharField(choices=[('explicit', 'Manual Review'), ('implied', 'Subject Preference Auto-Approval'), ('opt-in', 'Partial Approval'), ('opt-out', 'Withdrawn / Revoked')], default='explicit', max_length=50)),
                ('policy_evaluation_result', models.CharField(choices=[('compliant', 'Compliant'), ('non-compliant', 'Non-Compliant'), ('n/a', 'Not Applicable')], default='n/a', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('pending', 'Pending'), ('denied', 'Denied')], default='pending', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_permissions', models.JSONField(blank=True, default=list)),
                ('granted_permissions', models.JSONField(blank=True, default=list)),
                ('odrl_request', models.JSONField(blank=True, default=dict)),
                ('odrl_policy', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Patient Consent',
                'verbose_name_plural': 'Patient Consents',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('limited', 'Limited')], max_length=20)),
                ('reason', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('warning', 'Warning')], default='compliant', max_length=20)),
            ],
        ),
    ]
