# Generated by Django 6.0.3 on 2026-03-12 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(editable=False, help_text='Unique identifier for the consent record.', max_length=100, unique=True)),
                ('data_type', models.CharField(help_text="The type of data being consented for (e.g., 'Medical Records', 'Genomic Data').", max_length=255)),
                ('purpose', models.TextField(help_text='The specific purpose for which the data is being collected and processed.')),
                ('consent_type', models.CharField(choices=[('explicit', 'Explicit Consent'), ('implied', 'Implied Consent'), ('opt-in', 'Opt-in Consent'), ('opt-out', 'Opt-out Consent')], default='explicit', help_text='The mechanism by which consent was obtained.', max_length=50)),
                ('policy_evaluation_result', models.CharField(choices=[('compliant', 'Compliant'), ('non-compliant', 'Non-Compliant'), ('n/a', 'Not Applicable')], default='n/a', help_text='Result of the policy compliance evaluation.', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('pending', 'Pending'), ('denied', 'Denied')], default='pending', help_text='Current status of the consent (e.g., active, withdrawn, expired).', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the consent record was created.')),
                ('decision_date', models.DateTimeField(blank=True, help_text='Date and time when the patient made a decision (e.g., granted, withdrew).', null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Date and time when the consent automatically expires.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details about the consent.')),
                ('data_processor', models.ForeignKey(help_text='The data processor managing this consent.', on_delete=django.db.models.deletion.CASCADE, related_name='consents_processed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient or data subject providing consent.', on_delete=django.db.models.deletion.CASCADE, related_name='consents_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Consent',
                'verbose_name_plural': 'Patient Consents',
                'ordering': ['-created_date'],
            },
        ),
    ]
