# Generated by Django 6.0.4 on 2026-04-21 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consent",
            name="granted_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="consent",
            name="odrl_policy",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="consent",
            name="odrl_request",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="consent",
            name="requested_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="consent",
            name="consent_id",
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="consent",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("explicit", "Manual Review"),
                    ("implied", "Subject Preference Auto-Approval"),
                    ("opt-in", "Partial Approval"),
                    ("opt-out", "Withdrawn / Revoked"),
                ],
                default="explicit",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="consent",
            name="data_processor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="data_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consent",
            name="decision_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consent",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consent",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="consent",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents_as_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="policy_evaluation_result",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("non-compliant", "Non-Compliant"),
                    ("n/a", "Not Applicable"),
                ],
                default="n/a",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="purpose",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="consent",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                    ("denied", "Denied"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
