# Generated by Django 6.0.4 on 2026-04-22 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_consent_granted_permissions_consent_odrl_policy_and_more'),
        ('patients', '0004_consentpolicy_created_at_consentpolicy_odrl_rule_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('research', 'Research'), ('audit', 'Audit'), ('emergency', 'Emergency'), ('insurance', 'Insurance')], max_length=50)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('share', 'Share'), ('delete', 'Delete')], default='read', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('evaluated', 'Evaluated')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='patients.patient')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('limited', 'Limited')], max_length=20)),
                ('reason', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('warning', 'Warning')], default='compliant', max_length=20)),
                ('access_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='consents.accessrequest')),
                ('matched_consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='consents.consent')),
            ],
        ),
    ]
