# Generated by Django 6.0.5 on 2026-05-14 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='data_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='access_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='consents.accessrequest'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='matched_consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='consents.consent'),
        ),
    ]
