# Generated by Django 6.0.4 on 2026-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='data_type',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='consent',
            name='purpose',
            field=models.CharField(choices=[('treatment', 'Treatment'), ('research', 'Research'), ('audit', 'Audit'), ('emergency', 'Emergency'), ('insurance', 'Insurance')], default='research', max_length=100),
        ),
    ]
