# Generated by Django 6.0.4 on 2026-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_category', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('odrl_rule_uid', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data_category', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('treatment', 'Treatment'), ('mental_health', 'Mental Health'), ('billing', 'Billing'), ('lab_results', 'Lab Results'), ('medication', 'Medication'), ('allergies', 'Allergies'), ('immunization', 'Immunization')], default='diagnosis', help_text='Select the category of the medical record data.', max_length=100)),
                ('sensitivity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhs_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_category', models.CharField(blank=True, choices=[('diagnosis', 'Diagnosis'), ('treatment', 'Treatment'), ('mental_health', 'Mental Health'), ('billing', 'Billing'), ('lab_results', 'Lab Results'), ('medication', 'Medication'), ('allergies', 'Allergies'), ('immunization', 'Immunization')], max_length=100, null=True)),
            ],
        ),
    ]
