# Generated by Django 6.0.4 on 2026-04-23 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consents', '0003_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consentpolicy',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.custompermission'),
        ),
        migrations.AddField(
            model_name='consentpolicy',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AddField(
            model_name='consentpolicy',
            name='source_consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_policies', to='consents.consent'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consentpolicy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientpermission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientpermission',
            name='role_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rolepermission'),
        ),
        migrations.AddConstraint(
            model_name='consentpolicy',
            constraint=models.UniqueConstraint(fields=('patient', 'role', 'permission', 'data_category', 'source_consent'), name='uniq_patient_role_permission_scope'),
        ),
    ]
