# Generated by Django 6.0.3 on 2026-03-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_consentpolicy'),
        ('users', '0002_rename_permission_custompermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('role_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rolepermission')),
            ],
        ),
    ]
