# Generated by Django 6.0.3 on 2026-03-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpermission',
            name='data_category',
            field=models.CharField(blank=True, choices=[('diagnosis', 'Diagnosis'), ('treatment', 'Treatment'), ('mental_health', 'Mental Health'), ('billing', 'Billing'), ('lab_results', 'Lab Results'), ('medication', 'Medication'), ('allergies', 'Allergies'), ('immunization', 'Immunization')], max_length=100, null=True),
        ),
    ]
