# Generated by Django 6.0.4 on 2026-04-21 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consents", "0002_consent_granted_permissions_consent_odrl_policy_and_more"),
        ("patients", "0003_patientpermission"),
        ("users", "0002_rename_permission_custompermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentpolicy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consentpolicy",
            name="odrl_rule_uid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="consentpolicy",
            name="purpose",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="consentpolicy",
            name="source_consent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_policies",
                to="consents.consent",
            ),
        ),
        migrations.AddField(
            model_name="consentpolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="consentpolicy",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="consentpolicy",
            constraint=models.UniqueConstraint(
                fields=(
                    "patient",
                    "role",
                    "permission",
                    "data_category",
                    "source_consent",
                ),
                name="uniq_patient_role_permission_scope",
            ),
        ),
    ]
