# Generated by Django 6.0.4 on 2026-04-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_consentpolicy_created_at_consentpolicy_odrl_rule_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='record_status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sensitivity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nhs_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
